@startuml Sekvensdiagram
' Oppgave: 
' Lag et sekvensdiagram som viser hvordan flyten 
' mellom hvert lag i systemet kan være når en bruker ønsker å betale 
' for innhold på en slik tjeneste. Anta at kunden betaler med et 
' kredittkort. Bruk verb eller metodenavn som tekst over hver pil.

' Hoved ting som bruker,server og 3. parts betalingstjenester
title Sekvensdiagram for Abonnementbestilling
actor Bruker                   as bruker
participant Strømmetjeneste    as stream
database Server                as server
participant Betalingstjeneste  as 3rd

' Handlinger
bruker -> stream      : Kjøper abonnement
stream -> server      : authenticateOrder()
alt Riktig kortinformasjon
    server -> 3rd     : verifyCardInfo()
    3rd -> server     : cardAccepted()
    server -> stream  : updateUserPermissions()
    stream --> bruker : Gi tilgangsmelding 
else Feil kortinformasjon
    3rd -> server    : cardNotFound()
    server --> bruker : Gi feilmeldings detaljer
else Betalingstjeneste sperret bestilling
    'server -> 3rd     : verifyCardInfo()
    3rd --> server    : Noe gikk galt
    server --> bruker : Gi feilmeldings detaljer 
end
@enduml